x-domain-provider-keys: &domain-provider-keys
  PORKBUN_API_KEY: ${PORKBUN_API_KEY}
  PORKBUN_API_SECRET_KEY: ${PORKBUN_API_SECRET_KEY}

x-ntfy-environment: &ntfy-environment
  HOSTNAME: ${HOSTNAME}
  NTFY_TOKEN: ${NTFY_TOKEN}
  NTFY_TOPIC: ${NTFY_TOPIC}

services:
  caddy:
    container_name: caddy
    image: caddy-porkbun
    build: .
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - ./config:/etc/caddy:ro
      - /docker/caddy/data:/data:rw
      - /docker/caddy/config:/config:rw
    environment:
      DOMAIN: ${DOMAIN}
      <<: [*domain-provider-keys, *ntfy-environment]

networks:
  default:
    name: gateway_network
    ipam:
      config:
        - subnet: 172.18.0.0/16
