x-healthcheck-parameters: &healthcheck-parameters
  interval: 30s
  timeout: 10s
  start_period: 30s
  retries: 3

services:
  seerr:
    container_name: seerr
    image: seerr/seerr
    restart: unless-stopped
    init: true
    volumes:
      - /docker/seerr/config:/app/config:rw
    environment:
      TZ: ${TZ}
    healthcheck:
      test: wget -qO- --tries=1 http://localhost:5055/api/v1/status
      <<: *healthcheck-parameters
    depends_on:
      sonarr:
        condition: service_healthy
      radarr:
        condition: service_healthy

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/sonarr/config:/config:rw
      - /servarr/media:/media:rw
      - /servarr/downloads:/downloads:rw
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    healthcheck:
      test: curl -fsS localhost:8989/ping
      <<: *healthcheck-parameters
    depends_on:
      gluetun:
        condition: service_healthy

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/radarr/config:/config:rw
      - /servarr/media:/media:rw
      - /servarr/downloads:/downloads:rw
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    healthcheck:
      test: curl -fsS localhost:7878/ping
      <<: *healthcheck-parameters
    depends_on:
      gluetun:
        condition: service_healthy

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/prowlarr/config:/config:rw
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    healthcheck:
      test: curl -fsS localhost:9696/ping
      <<: *healthcheck-parameters
    depends_on:
      gluetun:
        condition: service_healthy

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - /docker/flaresolverr/config:/config:rw
    environment:
      LOG_LEVEL: debug
      TZ: ${TZ}
      DISABLE_MEDIA: true
    healthcheck:
      test: curl -fsS localhost:8191/health
      <<: *healthcheck-parameters
    depends_on:
      gluetun:
        condition: service_healthy
      prowlarr:
        condition: service_healthy